
version: '3.8'

services:

  # --- Servicio del Backend (Python/Flask) ---
  backend:
    build: .
    image: mi_app_backend:latest
    container_name: modelo_prediccion_backend
    ports:
      - "5001:5001"
    # Reinicia el contenedor automáticamente si falla
    restart: always

  # --- Servicio del Frontend (React/Nginx) ---
  frontend:
    build: ./prediccion-ina-app
    image: mi_app_frontend:latest
    container_name: modelo_prediccion_frontend
    ports:
      - "3000:80"
    # El frontend depende del backend. Esto asegura que el backend se inicie primero.
    depends_on:
      - backend
    # Reinicia el contenedor automáticamente si falla
    restart: always
